# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48d094291c55e8cf32e13db654e45c75be982048c0a4d1f84efd55d7832cb605999e899ecae30ac97286f6b08efb94fc2ac91336441e69bb67619bb799282f74

test:
  secret_key_base: 9dad3488418074b1ea08e101fae0a1906538055dd6d97944d6ac0e5988f1599164db45a2a9360b8f2697816253ab8ffe85e884e679ebacbb8c61ff0e18f38d3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
